### ISSUE TITLE
PHP 7

### ISSUE THREAD

**Issue by pe1mew** [mfreiholz/iF.SVNAdmin#118]
Today I ran in to a brainless update to ubuntu 16 (I know my fault). There I found that PHP7 is installed and I received the message:
> Wrong PHP version. The minimum required version is: 5.3

Although I like to understand that PHP 5.3 is supported and PHP 7 not, the message is somewhat disturbing.
Is there any way that PHP7 is supported? Or a workaround to solve this issue?
Thanks in advance. Cu, Remko

**Comment by IntelligentesTierMaulApollo13** [comment]
The problem is how the actual PHP version gets compared to the required one in function checkPHPVersion (file 'classes/util/global.func.php').
Apparently each number (major,minor,revision,etc.) gets compared separately, which has to fail now. (5.3.x vs 7.0.x  -> 7 higher than 5, but 0 not!).

Just replace the content of this function with 'return version_compare(PHP_VERSION,'5.3.0');' and you should be fine. version_compare is there for exactly this use case and available since PHP4.1

**Comment by pe1mew** [comment]
Hi, Thank you for looking in to this problem. I implemented the proposed code and it works like a charm again. Problem solved.

**Comment by kpld** [comment]
Usable,  thanks IntelligentesTierMaulApollo13.

**Comment by killdaclick** [comment]
Stable version v1.6.2 - same problem. Nothing fixed.
